#!/usr/bin/env python3
"""Generate port/loader/rel_loader_chunks.h from the L-reloc descriptor.

Closes LRELOC-P1 finding 2: rel_loader_chunks.h was a THIRD baked-address
artifact layer with no generator (the scope doc listed five layers; this one
was missed and had been hand-rolled for EXRAM in P1). This script keys off:

  1. port/descriptor/rel-modules-data.inc -- s_rel_chunk_ranges[] (542 rows),
     the descriptor-fixed linked [lo..hi) span of every REL chunk at the
     current batch bases. Range starts name the chunk entry symbols.
  2. The regenerated chunk tree under REL_GEN (--tree, default
     port/build/rel-out-fixed/generated/rels) -- every chunk file is named
     chunks/chunk_XXXX_rel1_<lo-hex>.c and defines `void func_<lo>(CPUState*)`.
     The tree symbol set MUST equal the descriptor range-start set 1:1; any
     drift fails generation loudly instead of rotting silently.

Output: guard-guarded header with one extern per unique chunk start (sorted
ascending) + the binary-search dispatch table `s_rel_loader_chunks[]` +
REL_LOADER_CHUNK_COUNT, byte-compatible with the P1 hand-rolled layout.

Run from repo root:  python3 scripts/port/gen_rel_loader_chunks.py [--check]
  --check   verify that the on-disk header matches regeneration exactly
            (byte-for-byte); exit 1 with a unified diff otherwise.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DESC = REPO / "port/descriptor/rel-modules-data.inc"
OUT = REPO / "port/loader/rel_loader_chunks.h"

RANGE_ROW_RE = re.compile(r"\{0x([0-9A-Fa-f]{8})u,\s*0x([0-9A-Fa-f]{8})u\},")
COUNT_RE = re.compile(r"#define\s+REL_MODULE_CHUNK_RANGE_COUNT\s+(\d+)u")
FUNC_DEF_RE = re.compile(r"^void func_([0-9A-Fa-f]{8})\(CPUState\* ctx\) \{", re.M)


def parse_chunk_ranges(inc_text: str) -> list[tuple[int, int]]:
    m = re.search(r"const ModernGekkoRange s_rel_chunk_ranges\[\] = \{(.*?)\n\};",
                  inc_text, re.S)
    if not m:
        raise SystemExit("FAIL: s_rel_chunk_ranges[] not found in descriptor inc")
    rows = [(int(a, 16), int(b, 16))
            for a, b in RANGE_ROW_RE.findall(m.group(1))]
    if not rows:
        raise SystemExit("FAIL: zero rows parsed from s_rel_chunk_ranges[]")
    return rows


def collect_tree_funcs(tree: Path) -> set[int]:
    funcs: set[int] = set()
    for c in tree.glob("*/chunks/*.c"):
        text = c.read_text(errors="replace")
        funcs.update(int(x, 16) for x in FUNC_DEF_RE.findall(text))
    return funcs


def build_header(rows: list[tuple[int, int]], count_macro: int) -> str:
    # Invariants: sorted ascending by lo, disjoint-or-touching, lo < hi,
    # row count == the descriptor's own count macro.
    if len(rows) != count_macro:
        raise SystemExit(f"FAIL: parsed {len(rows)} chunk rows but descriptor "
                         f"header declares {count_macro} "
                         "(REL_MODULE_CHUNK_RANGE_COUNT)")
    prev_hi = -1
    for i, (lo, hi) in enumerate(rows):
        if lo >= hi:
            raise SystemExit(f"FAIL: row {i} [{lo:#x}..{hi:#x}) not lo<hi")
        if lo < prev_hi:
            raise SystemExit(f"FAIL: row {i} lo {lo:#x} overlaps previous hi "
                             f"{prev_hi:#x} (rows must be sorted, disjoint)")
        prev_hi = hi

    lines = [
        "// Generated by scripts/port/gen_rel_loader_chunks.py from",
        "// port/descriptor/rel-modules-data.inc (chunk ranges at tree-inferred",
        "// bases) + the regenerated chunk-tree symbols.",
        "// One extern per REL chunk range start; the dispatch table maps a linked",
        "// address to its chunk function. Sorted ascending by start (binary search).",
        "#ifndef PORT_REL_LOADER_CHUNKS_H",
        "#define PORT_REL_LOADER_CHUNKS_H",
        "",
        "/* Total chunk rows; matches REL_MODULE_CHUNK_RANGE_COUNT from the descriptor. */",
        f"#define REL_LOADER_CHUNK_COUNT {len(rows)}u",
        "",
        '#include "core/cpu.h"',
        "",
    ]
    seen: set[int] = set()
    for lo, _hi in rows:
        if lo not in seen:
            lines.append(f"extern void func_{lo:08X}(CPUState* ctx);")
            seen.add(lo)
    lines += [
        "",
        "typedef struct RelLoaderChunkEntry {",
        "    uint32_t start;",
        "    uint32_t end;",
        "    void (*fn)(CPUState* ctx);",
        "} RelLoaderChunkEntry;",
        "",
        "static const RelLoaderChunkEntry s_rel_loader_chunks[] = {",
    ]
    for lo, hi in rows:
        lines.append(f"    {{0x{lo:08X}u, 0x{hi:08X}u, func_{lo:08X}}},")
    lines += ["};", "", "#endif /* PORT_REL_LOADER_CHUNKS_H */", ""]
    return "\n".join(lines)




def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--descriptor", type=Path, default=DESC,
                    help="rel-modules-data.inc to key off")
    ap.add_argument("--tree", type=Path,
                    default=REPO / "port/build/rel-out-fixed/generated/rels",
                    help="regenerated chunk tree (symbol cross-check)")
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--skip-tree-check", action="store_true",
                    help="skip the chunk-tree symbol cross-check")
    ap.add_argument("--check", action="store_true",
                    help="verify on-disk output matches regeneration; no write")
    args = ap.parse_args()

    inc_text = args.descriptor.read_text()
    macro_m = (COUNT_RE.search(inc_text)
               or COUNT_RE.search(args.descriptor.with_suffix(".h").read_text()))
    if not macro_m:
        raise SystemExit("FAIL: REL_MODULE_CHUNK_RANGE_COUNT not found in "
                         "descriptor .inc/.h")
    rows = parse_chunk_ranges(inc_text)

    if not args.skip_tree_check:
        tree_funcs = collect_tree_funcs(args.tree)
        desc_starts = sorted({lo for lo, _ in rows})
        if not tree_funcs:
            raise SystemExit(f"FAIL: no chunk functions found under {args.tree}")
        if sorted(tree_funcs) != desc_starts:
            missing = set(desc_starts) - tree_funcs
            extra = tree_funcs - set(desc_starts)
            raise SystemExit(
                f"FAIL: tree/descriptor drift — {len(missing)} ranges without a "
                f"chunk fn (e.g. {[f'{x:08X}' for x in sorted(missing)[:5]]}), "
                f"{len(extra)} tree fns without a range "
                f"(e.g. {[f'{x:08X}' for x in sorted(extra)[:5]]}). "
                "Regenerate the descriptor or the tree first.")
        print(f"tree check: {len(tree_funcs)} chunk fns == "
              f"{len(desc_starts)} descriptor range starts (1:1)")

    content = build_header(rows, int(macro_m.group(1)))

    if args.check:
        want = args.out.read_text()
        if want == content:
            print(f"CHECK OK: {args.out} byte-identical to regeneration "
                  f"({len(rows)} rows)")
            return 0
        diff = "".join(difflib.unified_diff(
            want.splitlines(True), content.splitlines(True),
            fromfile=str(args.out), tofile=f"{args.out} (regenerated)"))
        sys.stderr.write(diff[:8000])
        raise SystemExit("CHECK FAIL: on-disk header differs from regeneration")

    args.out.write_text(content)
    print(f"wrote {args.out}: {len(rows)} chunk rows, "
          f"{len({lo for lo, _ in rows})} extern decls")
    return 0


if __name__ == "__main__":
    sys.exit(main())
