// Generated by packaging/branding/make_icon.py -- do not edit.
#pragma once

namespace deepsea_emblem
{
constexpr int SIZE = 16;
constexpr const char* GRID[SIZE] = {
    "..SSSSSSSSSSSS..",
    ".SSSSSSkSSSSyyS.",
    "SSSSSSSkcSSyyyyS",
    "SSSSSSSkccSyyyyS",
    "SSSSSSSkcccSyySS",
    "SSSSSSSkrrrrSSSS",
    "SSSSSSSkcccccSSS",
    "SSSSSSSkccccccSS",
    "SSShhhhhhhhhhhSS",
    "SSSwhhhhhhhhhwSS",
    "1111wwwwwwwww111",
    "1ww1111111111ww1",
    "2222222ww2222222",
    "3333o33333333333",
    ".44444444o44444.",
    "..444444444444..",
};
struct Colour
{
  char key;
  unsigned rgb;
};
constexpr Colour PALETTE[] = {
    {'S', 0x5BC0F8},
    {'y', 0xFFD65A},
    {'k', 0x1F2740},
    {'c', 0xFFF6DC},
    {'r', 0xE4573D},
    {'h', 0xA45A2F},
    {'w', 0xFFFFFF},
    {'1', 0x2E7FE0},
    {'2', 0x1B5CC2},
    {'3', 0x0E3E96},
    {'4', 0x072B6E},
    {'o', 0x8FC4F5},
};
}  // namespace deepsea_emblem
